-- DO NOT EDIT THIS FILE. IT IS MANAGED BY THE SHELL AND FOLLOWS STRICT RULES
-- In other words, I ain't writing a lua parser for this, so please be a good boi/girl/whatever
hl.config({animations={enabled=0}})
hl.config({decoration={shadow={enabled=0}}})
hl.config({decoration={blur={enabled=0}}})
hl.config({general={gaps_in=0}})
hl.config({general={gaps_out=0}})
hl.config({general={border_size=1}})
hl.config({decoration={rounding=0}})
hl.config({general={allow_tearing=1}})
